import { SideBar } from '@/components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='pt-br' className='antialiased'>
      <body className={inter.className}>
        <div className='relative min-h-screen lg:grid lg:grid-cols-app'>
          <SideBar />
          <main className='w-screen px-4 pb-12 pt-24 lg:col-start-2 lg:w-auto lg:px-8 lg:pt-8'>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
